# ENV VARIABLES
export PATH="/usr/local/bin:$PATH"
export SVN_EDITOR="mvim"
export ERL_LIBS=/opt/erlang-libs
export RDOCOPT="-S -f html -T hanna"
export CLASSPATH="$CLASSPATH:/usr/local/Cellar/clojure-contrib/1.1.0/clojure-contrib.jar"
# completion
autoload -U compinit
compinit

# automatically enter directories without cd
setopt auto_cd

export EDITOR='mvim'

# aliases
if [ -e "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

# use vi
bindkey -v

# use incremental search
bindkey ^R history-incremental-search-backward

# expand functions in the prompt
setopt prompt_subst

# prompt
export PS1='$(git_prompt_info)[${SSH_CONNECTION+"%{$fg_bold[green]%}%n@%m:"}%{$fg_bold[green]%}%2c%{$reset_color%}] '

# ignore duplicate history entries
setopt histignoredups

# keep more history
export HISTSIZE=200

# rvm-install added line:
if [[ -s ~/.rvm/scripts/rvm ]] ; then source ~/.rvm/scripts/rvm ; fi

