export PATH="$HOME/bin:/Applications/Shoes.app/Contents/MacOS:/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin:/opt/subversion/bin:$PATH" 

# ENV VARIABLES
export RDOCOPT="-S -f html -T hanna"
export SVN_EDITOR="mvim"
export DYLD_LIBRARY_PATH="$MAGICK_HOME/lib"

# MacPorts Installer addition on 2009-04-08_at_09:04:53: adding an appropriate MANPATH variable for use with MacPorts.
export MANPATH=/opt/local/share/man:$MANPATH
# Finished adapting your MANPATH environment variable for use with MacPorts.

# == Initial template From JFerris
# completion
autoload -U compinit
compinit

# automatically enter directories without cd
setopt auto_cd

export EDITOR='mvim'

# aliases
if [ -e "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

# vi mode
bindkey -v

# use incremental search
bindkey ^R history-incremental-search-backward

# expand functions in the prompt
setopt prompt_subst

# prompt
export PS1='$(git_prompt_info)[${SSH_CONNECTION+"%{$fg_bold[green]%}%n@%m:"}%{$fg_bold[green]%}%2c%{$reset_color%}] '

# ignore duplicate history entries
setopt histignoredups

# keep more history
export HISTSIZE=200

# rvm-install added line:
if [[ -s ~/.rvm/scripts/rvm ]] ; then source ~/.rvm/scripts/rvm ; fi

