# ENV VARIABLES
export PATH="/usr/local/bin:/usr/local/mysql/bin:$PATH"
export SVN_EDITOR="mvim"
export RDOCOPT="-S -f html -T hanna"
export CLASSPATH="$CLASSPATH:/usr/local/Cellar/clojure-contrib/1.1.0/clojure-contrib.jar"
# completion
autoload -U compinit
compinit

export EDITOR='mate'

# aliases
if [ -e "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

# DON'T use mvim
bindkey -e

# use incremental search
bindkey ^R history-incremental-search-backward

# expand functions in the prompt
setopt prompt_subst

# ignore duplicate history entries
setopt histignoredups

# keep more history
export HISTSIZE=200

# rvm-install added line:
if [[ -s ~/.rvm/scripts/rvm ]] ; then source ~/.rvm/scripts/rvm ; fi

# this tests for the presence of rvm 
# if its loaded, it'll add the prompt
function rvm_prompt_info {
  ruby_version=$(~/.rvm/bin/rvm-prompt)
  if [ -n "$ruby_version" ]; then
    echo "[%{$fg_bold[grey]%}$ruby_version%{$reset_color%}]"
  fi
}

# prompt
export PS1='$(git_prompt_info)$(rvm_prompt_info)[${SSH_CONNECTION+"%{$fg_bold[green]%}%n@%m:"}%{$fg_bold[green]%}%2c%{$reset_color%}] '